HOST = '127.0.0.1'
PORT = '3306'
DATABASE = 'flask_websocket'
USERNAME = 'root'
PASSWORD = 'hongwei123'

DB_URI = f"mysql+pymysql://{USERNAME}:{PASSWORD}@{HOST}:{PORT}/{DATABASE}"

SQLALCHEMY_DATABASE_URI = DB_URI
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_ECHO = True

