"""empty message

Revision ID: 700d5c2e3bde
Revises: 18dee9bd9842
Create Date: 2020-08-17 09:28:43.161704

"""

# revision identifiers, used by Alembic.
revision = '700d5c2e3bde'
down_revision = '18dee9bd9842'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('c_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classes')
    # ### end Alembic commands ###
