from face_recognition.Ali import AliSimple
from face_recognition.Ali import AliMulti
from face_recognition.Baidu import BaiduSimple
from face_recognition.Baidu import BaiduMulti
from face_recognition.Huawei import HuaweiSimple
from face_recognition.Huawei import HuaweiMulti
from face_recognition.Tencent import TencentSingle
from face_recognition.Tencent import TencentMulti
from face_recognition.IflyTek import IFlyTekSimple
from face_recognition.IflyTek import IFlyTekMulti1
from face_recognition.IflyTek import IFlyTekMulti2